"""Shared plumbing for the docs/generated guardrail generators.

Everything the individual generators (diagrams, metrics, catalogs) have in
common lives here: repo paths, the ``docs/architecture.toml`` loader, the
module→component mapper, the grimp import-graph builder (memoized — it is the
slowest step and has several consumers), and the writer that stamps the
AUTOGENERATED header contract onto ``docs/generated/``.
"""

from __future__ import annotations

import functools
import pathlib
import tomllib

REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
GENERATED_DIR = REPO_ROOT / "docs" / "generated"
ARCH_TOML = REPO_ROOT / "docs" / "architecture.toml"

# Project identity comes from the [project] table in architecture.toml so this
# guardrail kit ports to another src-layout repo by editing only that file.
# root_package is required (no fallback — a missing/typo'd [project] must fail
# loudly rather than silently scan the wrong package). For a flat layout
# (package directly at the repo root) set src_layout = "".
#
# language selects the dependency-graph frontend: "python" (default, grimp
# import graph) or "cpp" (quoted-#include graph via the _cpp_graph adapter).
# For cpp there is no package directory — sources live directly under the
# layout dir and root_package is the logical prefix module names carry.
_PROJECT = tomllib.loads(ARCH_TOML.read_text(encoding="utf-8")).get("project", {})
ROOT_PACKAGE = _PROJECT["root_package"]
LANGUAGE = _PROJECT.get("language", "python")
_SRC_LAYOUT = _PROJECT.get("src_layout", "src")
_SRC_BASE = (REPO_ROOT / _SRC_LAYOUT) if _SRC_LAYOUT else REPO_ROOT
SRC_ROOT = _SRC_BASE if LANGUAGE == "cpp" else _SRC_BASE / ROOT_PACKAGE

# The include scanner and the size metrics must agree on what counts as a C++
# source file; headers are modules too (merged with their .cpp twin by stem).
CPP_SUFFIXES = (".h", ".hpp", ".c", ".cc", ".cpp")

_AUTOGEN_HEADER = (
    "<!-- AUTOGENERATED by tests/guardrail — do not edit by hand.\n"
    "     Regenerate with `make diagrams` (or `pytest tests/guardrail`). -->\n\n"
)


def with_header(body: str) -> str:
    """Prepend the AUTOGENERATED banner to a generated Markdown body.

    The single place the header contract lives. JSON artifacts (which cannot
    carry an HTML comment) deliberately do not call this.
    """
    return _AUTOGEN_HEADER + body


def load_architecture() -> dict:
    return tomllib.loads(ARCH_TOML.read_text(encoding="utf-8"))


def component_of(module: str, components: dict[str, list[str]]) -> str | None:
    """Map a module to its component by longest matching module-prefix."""
    best, best_len = None, -1
    for comp, prefixes in components.items():
        for pfx in prefixes:
            if (module == pfx or module.startswith(pfx + ".")) and len(pfx) > best_len:
                best, best_len = comp, len(pfx)
    return best


@functools.lru_cache(maxsize=1)
def build_import_graph():
    """Build (once per test session) the project's real dependency graph.

    For Python this is grimp's import graph; for C++ it is the quoted-include
    graph, duck-typed to the same surface (``.modules`` +
    ``find_modules_directly_imported_by``) so every consumer stays language-blind.
    """
    if LANGUAGE == "cpp":
        # The module only ships with the cpp adapter (short import line so
        # 88-width reflow can't strand the ignore comment).
        from tests.guardrail import _cpp_graph  # pyright: ignore

        return _cpp_graph.build_include_graph()
    import grimp  # local import keeps the heavy build out of collection time

    return grimp.build_graph(ROOT_PACKAGE)


def source_files() -> list[pathlib.Path]:
    """Every first-party source file under the source root, sorted."""
    if LANGUAGE == "cpp":
        return sorted(p for p in SRC_ROOT.rglob("*") if p.suffix in CPP_SUFFIXES)
    return sorted(SRC_ROOT.rglob("*.py"))


def module_paths() -> dict[str, list[pathlib.Path]]:
    """Module name -> its source files.

    Python is one file per module; C++ merges the ``.h``/``.cpp`` pair sharing
    a path stem into one module, mirroring Python's per-module granularity.
    """
    out: dict[str, list[pathlib.Path]] = {}
    for path in source_files():
        out.setdefault(module_name_of(path), []).append(path)
    return out


def module_files(modules: list[str]) -> list[pathlib.Path]:
    """Resolve module names to source files (packages recurse)."""
    files: list[pathlib.Path] = []
    for module in modules:
        rel = module[len(ROOT_PACKAGE) + 1 :].replace(".", "/")
        py = SRC_ROOT / f"{rel}.py"
        pkg = SRC_ROOT / rel
        if py.exists():
            files.append(py)
        elif pkg.is_dir():
            files.extend(sorted(pkg.rglob("*.py")))
    return sorted(set(files))


def module_name_of(path: pathlib.Path) -> str:
    """Dotted module name of a source file under the package source root."""
    rel = path.relative_to(SRC_ROOT).with_suffix("")
    parts = [ROOT_PACKAGE, *rel.parts]
    if parts[-1] == "__init__":
        parts = parts[:-1]
    return ".".join(parts)


def write(name: str, content: str) -> pathlib.Path:
    """Write a generated artifact under ``docs/generated/`` (subpaths allowed)."""
    out = GENERATED_DIR / name
    out.parent.mkdir(parents=True, exist_ok=True)
    # newline="\n" pins LF so regeneration is byte-identical on Windows too
    # (the CI drift gate compares bytes).
    out.write_text(content, encoding="utf-8", newline="\n")
    return out
