"""Deterministic Mermaid diagram generation from the real lithos_loom code.

Two generators, both driven by ``docs/architecture.toml``:

* :func:`render_domain_model` — a class diagram of the domain dataclasses /
  Pydantic models, extracted statically with :mod:`ast` (no imports, no side
  effects). Cardinalities are derived from field annotations
  (``list[X]`` -> ``0..*``, ``X | None`` -> ``0..1``, bare ``X`` -> ``1``).
* :func:`render_component_diagram` — a component dependency graph computed from
  the *real* import graph via :mod:`grimp`, grouped into the components declared
  in ``architecture.toml``.

Both emit fenced ```mermaid markdown so GitHub and Obsidian render them inline.
Everything is sorted so identical code always yields byte-identical output —
that is what makes the CI drift check meaningful.
"""

from __future__ import annotations

import ast
import pathlib
import re
import tomllib
from dataclasses import dataclass

ROOT_PACKAGE = "lithos_loom"
REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
SRC_ROOT = REPO_ROOT / "src" / ROOT_PACKAGE
GENERATED_DIR = REPO_ROOT / "docs" / "generated"
ARCH_TOML = REPO_ROOT / "docs" / "architecture.toml"

_AUTOGEN_HEADER = (
    "<!-- AUTOGENERATED by tests/guardrail — do not edit by hand.\n"
    "     Regenerate with `make diagrams` (or `pytest tests/guardrail`). -->\n\n"
)


# --------------------------------------------------------------------------- #
# architecture.toml
# --------------------------------------------------------------------------- #
def load_architecture() -> dict:
    return tomllib.loads(ARCH_TOML.read_text(encoding="utf-8"))


def component_of(module: str, components: dict[str, list[str]]) -> str | None:
    """Map a module to its component by longest matching module-prefix."""
    best, best_len = None, -1
    for comp, prefixes in components.items():
        for pfx in prefixes:
            if (module == pfx or module.startswith(pfx + ".")) and len(pfx) > best_len:
                best, best_len = comp, len(pfx)
    return best


# --------------------------------------------------------------------------- #
# Component diagram (grimp = real import graph)
# --------------------------------------------------------------------------- #
def component_edges(components: dict[str, list[str]]) -> set[tuple[str, str]]:
    import grimp  # local import keeps the heavy build out of collection time

    graph = grimp.build_graph(ROOT_PACKAGE)
    edges: set[tuple[str, str]] = set()
    for module in graph.modules:
        src = component_of(module, components)
        if src is None:
            continue
        for imported in graph.find_modules_directly_imported_by(module):
            dst = component_of(imported, components)
            if dst is not None and dst != src:
                edges.add((src, dst))
    return edges


def render_component_diagram() -> str:
    arch = load_architecture()
    components: dict[str, list[str]] = arch["components"]
    tiers: dict[str, list[str]] = arch.get("tiers", {})
    edges = component_edges(components)

    lines = ["```mermaid", "graph TD"]
    placed: set[str] = set()
    for tier in sorted(tiers):
        members = [c for c in sorted(tiers[tier]) if c in components]
        if not members:
            continue
        lines.append(f"  subgraph {tier}")
        for comp in members:
            lines.append(f"    {comp}")
            placed.add(comp)
        lines.append("  end")
    for comp in sorted(components):
        if comp not in placed:
            lines.append(f"  {comp}")
    for src, dst in sorted(edges):
        lines.append(f"  {src} --> {dst}")
    lines.append("```")
    return _AUTOGEN_HEADER + "# Component dependencies\n\n" + "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
# Domain class diagram (ast = static source scan)
# --------------------------------------------------------------------------- #
@dataclass(frozen=True)
class _Assoc:
    src: str
    card: str
    dst: str
    label: str


def _module_files(modules: list[str]) -> list[pathlib.Path]:
    files: list[pathlib.Path] = []
    for module in modules:
        rel = module[len(ROOT_PACKAGE) + 1 :].replace(".", "/")
        py = SRC_ROOT / f"{rel}.py"
        pkg = SRC_ROOT / rel
        if py.exists():
            files.append(py)
        elif pkg.is_dir():
            files.extend(sorted(pkg.rglob("*.py")))
    return sorted(set(files))


def _is_dataclass(node: ast.ClassDef) -> bool:
    for dec in node.decorator_list:
        func = dec.func if isinstance(dec, ast.Call) else dec
        if isinstance(func, ast.Name) and func.id == "dataclass":
            return True
        if isinstance(func, ast.Attribute) and func.attr == "dataclass":
            return True
    return False


def _is_pydantic(node: ast.ClassDef, model_names: set[str]) -> bool:
    for base in node.bases:
        name = base.id if isinstance(base, ast.Name) else getattr(base, "attr", "")
        if name == "BaseModel" or name in model_names:
            return True
    return False


def _discover_models(files: list[pathlib.Path]) -> list[ast.ClassDef]:
    all_classes: list[ast.ClassDef] = []
    for path in files:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        all_classes.extend(n for n in ast.walk(tree) if isinstance(n, ast.ClassDef))
    names = {c.name for c in all_classes}
    models = [
        c
        for c in all_classes
        if (_is_dataclass(c) or _is_pydantic(c, names)) and not c.name.startswith("_")
    ]
    seen: set[str] = set()
    unique = []
    for c in sorted(models, key=lambda c: c.name):
        if c.name not in seen:
            seen.add(c.name)
            unique.append(c)
    return unique


def _fields(cls: ast.ClassDef) -> list[tuple[str, str]]:
    out: list[tuple[str, str]] = []
    for stmt in cls.body:
        if isinstance(stmt, ast.AnnAssign) and isinstance(stmt.target, ast.Name):
            fname = stmt.target.id
            if fname.startswith("_"):
                continue
            out.append((fname, ast.unparse(stmt.annotation)))
    return out


_MANY = re.compile(r"\b(list|set|frozenset|tuple|Sequence|Iterable|Collection)\s*\[")


def _cardinality(annotation: str, target: str) -> str:
    if _MANY.search(annotation) and target in annotation:
        return "0..*"
    if "Optional[" in annotation or "| None" in annotation or "None |" in annotation:
        return "0..1"
    return "1"


def _associations(models: list[ast.ClassDef]) -> list[_Assoc]:
    names = {c.name for c in models}
    seen: set[tuple[str, str]] = set()
    result: list[_Assoc] = []
    for cls in models:
        for fname, anno in _fields(cls):
            for target in sorted(names):
                if target == cls.name:
                    continue
                if re.search(rf"\b{re.escape(target)}\b", anno):
                    pair = (min(cls.name, target), max(cls.name, target))
                    if pair in seen:
                        continue
                    seen.add(pair)
                    result.append(
                        _Assoc(cls.name, _cardinality(anno, target), target, fname)
                    )
    return sorted(result, key=lambda a: (a.src, a.dst, a.label))


def render_domain_model() -> str:
    arch = load_architecture()
    domain = arch.get("domain", {})
    include = domain.get("include_modules") or [ROOT_PACKAGE]
    exclude = set(domain.get("exclude_modules", []))
    files = [
        f
        for f in _module_files(include)
        if not any(
            f == SRC_ROOT / (m[len(ROOT_PACKAGE) + 1 :].replace(".", "/") + ".py")
            for m in exclude
        )
    ]
    models = _discover_models(files)
    model_names = {c.name for c in models}

    lines = ["```mermaid", "classDiagram"]
    for cls in models:
        scalar = [
            (n, t) for n, t in _fields(cls) if not any(m in t for m in model_names)
        ]
        if scalar:
            lines.append(f"  class {cls.name} {{")
            for n, t in scalar:
                lines.append(f"    +{n} {t}")
            lines.append("  }")
        else:
            lines.append(f"  class {cls.name}")
    for a in _associations(models):
        lines.append(f'  {a.src} "1" --> "{a.card}" {a.dst} : {a.label}')
    lines.append("```")
    return _AUTOGEN_HEADER + "# Domain model\n\n" + "\n".join(lines) + "\n"


# --------------------------------------------------------------------------- #
def write(name: str, content: str) -> pathlib.Path:
    GENERATED_DIR.mkdir(parents=True, exist_ok=True)
    out = GENERATED_DIR / name
    out.write_text(content, encoding="utf-8")
    return out
