"""Regenerate the per-component drill-down pages (drift-checked in CI)."""

from __future__ import annotations

import re

from tests.guardrail import _component_pages as cp
from tests.guardrail._common import load_architecture, write

# Component keys are emitted verbatim as Mermaid node ids and as
# components/<name>.md paths, so they must be identifier/path-safe.
_SAFE_COMPONENT = re.compile(r"^[A-Za-z][A-Za-z0-9]*$")


def test_generate_component_pages() -> None:
    pages = cp.render_all()
    components = load_architecture()["components"]
    assert set(pages) == {f"components/{c}.md" for c in components}
    for relpath, content in pages.items():
        out = write(relpath, content)
        assert out.exists()
        assert content.startswith("<!-- AUTOGENERATED")


def test_component_names_are_safe_ids() -> None:
    """Guards the convention: component keys are used raw as Mermaid ids and paths."""
    bad = sorted(
        c for c in load_architecture()["components"] if not _SAFE_COMPONENT.match(c)
    )
    assert not bad, (
        "component names are emitted verbatim as Mermaid node ids and "
        f"components/<name>.md paths; these are not identifier/path-safe: {bad}"
    )


def test_every_component_has_a_description() -> None:
    arch = load_architecture()
    docs = arch.get("component_docs", {})
    missing = sorted(c for c in arch["components"] if not docs.get(c))
    assert not missing, f"components missing a [component_docs] one-liner: {missing}"
