"""``obsidian-projection`` subscription handler (Slice 1 US8).

Turns ``lithos.task.{created,updated,completed,cancelled}`` events into
a markdown file at ``vault_path / tasks_file`` that the Obsidian Tasks
plugin can query.

Line shape for US8 is deliberately minimal:

    %% Auto-generated by lithos-loom. Hand edits will be overwritten. ... %%

    - [ ] <title> 🆔 lithos:<id>
    - [ ] <other title> 🆔 lithos:<other id>

US9 adds `📅 <date>`, `#project/<slug>`, `#lithos/<route-name>`; US10
adds priority emoji; US11 adds `⛔` dependency markers; US13 adds
completed/cancelled lingering with `✅`/`❌`. For US8 the file holds
only currently-actionable open tasks; completed/cancelled events
remove the line.

The handler maintains an in-process state dict ``{task_id → line}``.
The SSE source's bootstrap replays all open tasks as ``created``
events on daemon startup, so state rebuilds naturally on restart —
same idempotency contract as ``RouteRunner._processed_tasks``.

File writes are atomic: write to ``<path>.tmp``, fsync, then
``os.replace`` onto the final path. Content-hash dedup ("only write
when content has actually changed") is US14.
"""

from __future__ import annotations

import asyncio
import logging
import os
from pathlib import Path
from typing import Any

from lithos_loom.bus import Event
from lithos_loom.config import LoomConfig
from lithos_loom.lithos_client import Task
from lithos_loom.subscriptions._human_actionable import is_human_actionable

__all__ = ["make_handler"]

logger = logging.getLogger(__name__)

_UPSERT_EVENTS = frozenset({"lithos.task.created", "lithos.task.updated"})
_REMOVAL_EVENTS = frozenset({"lithos.task.completed", "lithos.task.cancelled"})

_FILE_HEADER = (
    "%% Auto-generated by lithos-loom (US7+). Hand edits will be "
    "overwritten on the next event. Use Obsidian capture macros for "
    "new tasks (Slice 3+). %%"
)


def make_handler(cfg: LoomConfig) -> Any:
    """Build a stateful obsidian-projection handler bound to ``cfg``.

    The returned coroutine closes over a per-call state dict and the
    target ``tasks_file`` path. Each invocation of ``make_handler``
    produces a fresh handler with its own state — safe to wire
    multiple subscriptions in the same child if ever needed.

    ``cfg.obsidian_sync`` must be set; the obsidian-sync child's spawn
    gate guarantees this, but we assert for defensive readability.
    """
    obs = cfg.obsidian_sync
    if obs is None:
        raise RuntimeError(
            "make_handler called without [obsidian_sync] config; the "
            "supervisor's spawn gate should have prevented this"
        )

    tasks_path = obs.vault_path / obs.tasks_file
    state: dict[str, str] = {}

    async def handle(event: Event, ctx: Any) -> None:
        task = _task_from_payload(event.payload)
        if event.type in _REMOVAL_EVENTS:
            removed = state.pop(task.id, None)
            if removed is not None:
                ctx.logger.debug(
                    "obsidian-projection: removed %s on %s", task.id, event.type
                )
        elif event.type in _UPSERT_EVENTS:
            if is_human_actionable(task, cfg.routes, obs):
                state[task.id] = _render_line(task)
                ctx.logger.debug(
                    "obsidian-projection: upserted %s on %s", task.id, event.type
                )
            elif state.pop(task.id, None) is not None:
                ctx.logger.debug(
                    "obsidian-projection: removed (no longer actionable) %s on %s",
                    task.id,
                    event.type,
                )
            # Task wasn't tracked and isn't actionable now — no state change.
            else:
                return
        else:
            # Subscription.event_types should filter unwanted types out
            # before we get here; debug-log so a config drift surfaces.
            ctx.logger.debug(
                "obsidian-projection: ignoring unexpected event type %s", event.type
            )
            return

        await _write_tasks_file_atomic(tasks_path, _render_file(state))

    return handle


# ── helpers ────────────────────────────────────────────────────────────


def _task_from_payload(payload: Any) -> Task:
    """Reconstruct a :class:`Task` from the SSE source's published payload.

    The :class:`~lithos_loom.sources.lithos_event_stream.LithosEventStream`
    publishes the full Task shape (id, title, status, tags, metadata,
    claims), so this is just dict-lookups, not a re-fetch.
    """
    return Task(
        id=str(payload["id"]),
        title=str(payload.get("title", "")),
        status=str(payload.get("status", "")),
        tags=tuple(payload.get("tags") or ()),
        metadata=dict(payload.get("metadata") or {}),
        claims=tuple(payload.get("claims") or ()),
    )


def _render_line(task: Task) -> str:
    """Render one Tasks-plugin task line for an open task.

    Titles with embedded newlines (rare in Lithos but possible) are
    collapsed to spaces so the markdown line stays single-line. The
    ``🆔 lithos:<id>`` marker is what lets US14's dedup and future
    enrichment stories identify the same task across rewrites.
    """
    title = " ".join(task.title.split())  # collapse \n, \r, runs of spaces
    return f"- [ ] {title} 🆔 lithos:{task.id}"


def _render_file(state: dict[str, str]) -> str:
    """Render the full file content from the state dict.

    Sorted by task id for deterministic output (cheap stability for
    tests and for content-hash dedup once US14 lands).
    """
    if not state:
        return _FILE_HEADER + "\n"
    lines = [_FILE_HEADER, ""]
    for tid in sorted(state):
        lines.append(state[tid])
    lines.append("")
    return "\n".join(lines)


async def _write_tasks_file_atomic(path: Path, content: str) -> None:
    """Atomically rewrite ``path`` with ``content``.

    Strategy: write to ``<path>.tmp``, fsync, then ``os.replace`` onto
    the final path. ``os.replace`` is atomic on POSIX. Creates
    ``path.parent`` if absent.

    Synchronous I/O inside an async function — fine for the
    vault-sized files this serves (<10kB typical). Move to
    ``asyncio.to_thread`` if write latency under load becomes an issue.
    """
    path.parent.mkdir(parents=True, exist_ok=True)
    tmp = path.with_suffix(path.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    fd = os.open(tmp, os.O_RDONLY)
    try:
        os.fsync(fd)
    finally:
        os.close(fd)
    os.replace(tmp, path)
    # Yield once so the async caller can be cancelled cleanly between
    # events even under back-to-back delivery.
    await asyncio.sleep(0)
