"""PR delivery + the Copilot review round (T9, PRD decision #9).

After the panel approves, the trusted HOST-side plugin process (never an
agent container — agents have no push credentials) pushes the branch, opens a
PR via ``gh``, and runs one **Copilot round**:

    push + open PR -> request Copilot -> poll for its review
      -> translate inline comments into a synthetic review handoff
         (Copilot is a reviewer DATA SOURCE, not a panel member — it can only
         review a PR, which exists only after approval)
      -> ONE coder fix round on the resumed session (no panel re-review)
      -> T4 test gate on the fix commit; RED => the fix is NOT pushed
      -> reply to each Copilot comment thread ("Fixed in <sha> — ..." /
         "Not changed — ..." for disputes), marked as automated.

No Copilot re-request — one round is the bound; a re-trigger loop is future
work. A Copilot timeout degrades gracefully: the PR stands as approved.

Layered like :mod:`containers` / :mod:`test_gate`: pure builders up top,
thin ``gh`` / ``git`` wrappers at the bottom (monkeypatched in tests).
"""

from __future__ import annotations

import json
import logging
import re
import subprocess
import time
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

COPILOT_LOGIN = "copilot-pull-request-reviewer[bot]"
# Copilot's reviewer slug for the requested_reviewers POST (the display name
# "Copilot" silently no-ops — learned the hard way on this repo).
COPILOT_REVIEWER = "copilot-pull-request-reviewer[bot]"
AUTOMATED_MARKER = "_(automated reply by story-develop)_"
DEFAULT_COPILOT_TIMEOUT = 600  # seconds; observed turnaround is ~2-4 min
COPILOT_POLL_SECONDS = 15


@dataclass(frozen=True)
class CopilotComment:
    """One Copilot inline comment, as fetched from the PR."""

    comment_id: int
    path: str
    line: int | None
    body: str


@dataclass(frozen=True)
class DeliveryOutcome:
    """What the delivery phase did (for the summary + Lithos posting)."""

    pr_url: str
    pr_number: int
    pushed: bool = True
    copilot_requested: bool = False
    copilot_reviewed: bool = False
    comments_count: int = 0
    fix_committed: bool = False
    fix_pushed: bool = False
    fix_gate_verdict: str | None = None  # GREEN | RED | TIMEOUT | None (no gate)
    replies_posted: int = 0
    notes: tuple[str, ...] = field(default=())


# --- pure builders ------------------------------------------------------------


def parse_issue_ref(github_issue_url: str) -> tuple[str, int] | None:
    """``https://github.com/o/r/issues/42`` -> ``("o/r", 42)``; None if not."""
    m = re.match(
        r"https://github\.com/([^/]+/[^/]+)/issues/(\d+)/?$",
        github_issue_url.strip(),
    )
    if not m:
        return None
    return m.group(1), int(m.group(2))


def closes_line(github_issue_url: str | None, pr_repo: str) -> str:
    """The ``Closes …`` line linking the PR to its source issue, or ``""``.

    Same-repo issues use the short ``#N`` form; cross-repo issues need the
    full ``owner/repo#N`` form for GitHub's closing keywords to bind.
    """
    if not github_issue_url:
        return ""
    ref = parse_issue_ref(github_issue_url)
    if ref is None:
        return ""
    repo, number = ref
    if repo.lower() == pr_repo.lower():
        return f"Closes #{number}"
    return f"Closes {repo}#{number}"


def build_pr_body(
    *,
    description: str,
    acceptance_criteria: str | None,
    reviews_summary: str,
    rounds: int,
    gate_verdict: str | None,
    cost_usd: float,
    task_id: str | None,
    issue_closes: str = "",
) -> str:
    """The generated PR body: provenance + verdicts, not the whole log."""
    parts = ["## What", "", description.strip(), ""]
    if issue_closes:
        parts += [issue_closes, ""]
    if acceptance_criteria:
        parts += ["## Acceptance criteria", "", acceptance_criteria.strip(), ""]
    parts += [
        "## Review",
        "",
        f"- verdicts: {reviews_summary}",
        f"- rounds: {rounds}",
    ]
    if gate_verdict:
        parts.append(f"- test gate: {gate_verdict}")
    parts.append(f"- agent cost: ${cost_usd:.2f}")
    if task_id:
        parts.append(f"- Lithos task: `{task_id}`")
    parts += [
        "",
        "Per-round commits are intentional (the dialogue history); "
        "squash-merge keeps main clean.",
        "",
        "🤖 Generated by lithos-loom story-develop",
    ]
    return "\n".join(parts)


def comments_to_handoff_text(comments: list[CopilotComment]) -> str:
    """Render Copilot's inline comments as a synthetic review handoff.

    Findings carry blank ids (the ``copilot`` ledger assigns them) and
    ``minor`` severity (Copilot expresses no severity; the round is
    non-gating either way — the PR is already open).
    """
    lines = [
        "## Status: FINDINGS",
        "## Summary",
        f"Copilot left {len(comments)} inline comment(s) on the PR.",
        "## Findings",
    ]
    for c in comments:
        loc = f"{c.path}:{c.line}" if c.line else c.path
        rationale = " ".join(c.body.split())  # one line; parser-safe
        lines += [
            "- finding_id:",
            "  severity: minor",
            "  status: open",
            f'  files: ["{loc}"]',
            f"  rationale: {rationale}",
        ]
    return "\n".join(lines) + "\n"


def reply_body(
    *,
    fixed: bool,
    sha: str | None,
    coder_response: str,
    held_back_verdict: str | None = None,
) -> str:
    """The per-thread reply: fix reference, held-back notice, or pushback.

    *held_back_verdict* covers the committed-but-not-pushed case (RED
    regression gate): the code DID change, so "Not changed" would be
    misleading — say what happened instead.
    """
    response = coder_response.strip() or "(no further detail given)"
    if held_back_verdict is not None:
        head = (
            f"A fix was prepared but NOT pushed — the regression test gate "
            f"came back {held_back_verdict} on the fix commit (see the PR "
            f"comment). Intended change: {response}"
        )
    elif fixed and sha:
        head = f"Fixed in {sha[:10]} — {response}"
    elif fixed:
        head = f"Addressed — {response}"
    else:
        head = f"Not changed — {response}"
    return f"{head}\n\n{AUTOMATED_MARKER}"


# --- thin gh / git wrappers (monkeypatched in tests) ---------------------------


def _run(
    args: list[str], *, cwd: Path, timeout: int = 120
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        args, cwd=cwd, capture_output=True, text=True, timeout=timeout
    )


def push_branch(wt: Path, branch: str) -> None:
    """Host-side push of the worktree branch to origin. Raises on failure."""
    proc = _run(["git", "push", "-u", "origin", branch], cwd=wt, timeout=300)
    if proc.returncode != 0:
        raise RuntimeError(f"git push failed: {proc.stderr.strip()}")


def repo_name_with_owner(wt: Path) -> str:
    """``owner/repo`` of the worktree's origin (via gh)."""
    proc = _run(
        ["gh", "repo", "view", "--json", "nameWithOwner", "-q", ".nameWithOwner"],
        cwd=wt,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"gh repo view failed: {proc.stderr.strip()}")
    return proc.stdout.strip()


def create_pr(wt: Path, *, branch: str, base: str, title: str, body: str) -> str:
    """Open the PR; returns its URL. Raises on failure."""
    proc = _run(
        [
            "gh",
            "pr",
            "create",
            "--head",
            branch,
            "--base",
            base,
            "--title",
            title,
            "--body",
            body,
        ],
        cwd=wt,
        timeout=300,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"gh pr create failed: {proc.stderr.strip()}")
    url = proc.stdout.strip().splitlines()[-1].strip()
    if not url.startswith("http"):
        raise RuntimeError(f"gh pr create returned no URL: {proc.stdout!r}")
    return url


def pr_number_from_url(url: str) -> int:
    m = re.search(r"/pull/(\d+)", url)
    if not m:
        raise RuntimeError(f"cannot parse PR number from {url!r}")
    return int(m.group(1))


def request_copilot(wt: Path, repo: str, pr_number: int) -> bool:
    """Request the Copilot reviewer; False (logged) on failure — non-fatal."""
    proc = _run(
        [
            "gh",
            "api",
            "-X",
            "POST",
            f"repos/{repo}/pulls/{pr_number}/requested_reviewers",
            "-f",
            f"reviewers[]={COPILOT_REVIEWER}",
        ],
        cwd=wt,
    )
    if proc.returncode != 0:
        logger.warning(
            "story-develop: requesting Copilot on %s#%d failed: %s",
            repo,
            pr_number,
            proc.stderr.strip(),
        )
        return False
    return True


def _copilot_review_exists(wt: Path, repo: str, pr_number: int) -> bool:
    proc = _run(["gh", "api", f"repos/{repo}/pulls/{pr_number}/reviews"], cwd=wt)
    if proc.returncode != 0:
        return False
    try:
        reviews: list[dict[str, Any]] = json.loads(proc.stdout)
    except json.JSONDecodeError:
        return False
    return any((r.get("user") or {}).get("login") == COPILOT_LOGIN for r in reviews)


def fetch_copilot_comments(wt: Path, repo: str, pr_number: int) -> list[CopilotComment]:
    """Copilot's top-level inline comments on the PR (replies excluded)."""
    proc = _run(["gh", "api", f"repos/{repo}/pulls/{pr_number}/comments"], cwd=wt)
    if proc.returncode != 0:
        return []
    try:
        raw: list[dict[str, Any]] = json.loads(proc.stdout)
    except json.JSONDecodeError:
        return []
    out: list[CopilotComment] = []
    for c in raw:
        if (c.get("user") or {}).get("login") != COPILOT_LOGIN:
            continue
        if c.get("in_reply_to_id"):  # thread replies are not findings
            continue
        out.append(
            CopilotComment(
                comment_id=int(c["id"]),
                path=str(c.get("path") or ""),
                line=c.get("line") or c.get("original_line"),
                body=str(c.get("body") or ""),
            )
        )
    return out


def wait_for_copilot(
    wt: Path,
    repo: str,
    pr_number: int,
    *,
    timeout: int,
    poll_seconds: int = COPILOT_POLL_SECONDS,
) -> bool:
    """Poll until Copilot's review lands; False on timeout."""
    deadline = time.monotonic() + timeout
    while time.monotonic() < deadline:
        if _copilot_review_exists(wt, repo, pr_number):
            return True
        time.sleep(min(poll_seconds, max(1, deadline - time.monotonic())))
    return False


def post_thread_reply(
    wt: Path, repo: str, pr_number: int, comment_id: int, body: str
) -> bool:
    proc = _run(
        [
            "gh",
            "api",
            "-X",
            "POST",
            f"repos/{repo}/pulls/{pr_number}/comments/{comment_id}/replies",
            "-f",
            f"body={body}",
        ],
        cwd=wt,
    )
    if proc.returncode != 0:
        logger.warning(
            "story-develop: reply to comment %d failed: %s",
            comment_id,
            proc.stderr.strip(),
        )
        return False
    return True


def post_pr_comment(wt: Path, pr_number: int, body: str) -> bool:
    proc = _run(["gh", "pr", "comment", str(pr_number), "--body", body], cwd=wt)
    if proc.returncode != 0:
        logger.warning("story-develop: PR comment failed: %s", proc.stderr.strip())
        return False
    return True


# --- orchestration --------------------------------------------------------------


def deliver(
    config,
    result,
    *,
    no_copilot: bool = False,
    copilot_timeout: int = DEFAULT_COPILOT_TIMEOUT,
    coder_timeout: int = 3600,
    github_issue_url: str | None = None,
    task_id: str | None = None,
) -> DeliveryOutcome:
    """Push the approved branch, open the PR, run the Copilot round.

    Imports the develop-module helpers lazily to keep the import graph
    one-directional (develop never imports this module).
    """
    from ...runner import git
    from . import containers, handoff
    from .develop import (
        _build_run_cmd,
        _render,
        _render_findings,
        _resolve_gate_command,
        _run_gate,
    )
    from .findings import FindingLedger
    from .turns import run_turn

    wt: Path = result.worktree
    notes: list[str] = []

    push_branch(wt, result.branch)
    repo = repo_name_with_owner(wt)
    title = config.description.strip().splitlines()[0][:90]
    body = build_pr_body(
        description=config.description,
        acceptance_criteria=config.acceptance_criteria,
        reviews_summary=" ".join(f"[{r.reviewer}]={r.status}" for r in result.reviews),
        rounds=result.rounds,
        gate_verdict=result.test_gate.verdict if result.test_gate else None,
        cost_usd=result.total_cost_usd,
        task_id=task_id,
        issue_closes=closes_line(github_issue_url, repo),
    )
    pr_url = create_pr(
        wt, branch=result.branch, base=config.base_branch, title=title, body=body
    )
    pr_number = pr_number_from_url(pr_url)
    logger.info("story-develop %s: opened PR %s", config.run_id, pr_url)

    if no_copilot:
        return DeliveryOutcome(pr_url=pr_url, pr_number=pr_number, notes=tuple(notes))

    requested = request_copilot(wt, repo, pr_number)
    if not requested:
        notes.append("Copilot review request failed; respond manually")
        return DeliveryOutcome(pr_url=pr_url, pr_number=pr_number, notes=tuple(notes))
    if not wait_for_copilot(wt, repo, pr_number, timeout=copilot_timeout):
        notes.append(
            f"Copilot review not received within {copilot_timeout}s; "
            "respond manually when it lands"
        )
        return DeliveryOutcome(
            pr_url=pr_url,
            pr_number=pr_number,
            copilot_requested=True,
            notes=tuple(notes),
        )

    comments = fetch_copilot_comments(wt, repo, pr_number)
    if not comments:
        return DeliveryOutcome(
            pr_url=pr_url,
            pr_number=pr_number,
            copilot_requested=True,
            copilot_reviewed=True,
            notes=tuple(notes),
        )

    # --- synthetic copilot review -> ledger ids -> ONE coder fix round ------
    fix_round = result.rounds + 1
    synthetic = comments_to_handoff_text(comments)
    parsed = handoff.parse_review_handoff(synthetic)
    ledger = FindingLedger("copilot")
    canonical = ledger.apply_review(parsed, fix_round)
    id_to_comment = {f.finding_id: c for f, c in zip(canonical, comments, strict=True)}
    # keep the synthetic review on disk: conversation-log + audit parity
    synthetic_path = config.handoff_dir / handoff.reviewer_handoff_name(
        fix_round, "copilot"
    )
    synthetic_path.write_text(synthetic, encoding="utf-8")

    coder_handoff = handoff.coder_handoff_name(fix_round)
    prompt = _render(
        handoff.load_prompt("copilot_fix.md"),
        pr_url=pr_url,
        acceptance_criteria=config.effective_acceptance_criteria,
        findings=_render_findings(canonical),
        handoff_file=coder_handoff,
    )
    name, run_cmd = _build_run_cmd(
        config,
        agent="coder",
        config_dir=config.coder_config_dir,
        wt=wt,
        read_only=False,
    )
    try:
        containers.start_container(run_cmd)
        turn = run_turn(
            container=name,
            prompt=prompt,
            session_id=result.coder_session,
            resume=True,
            timeout=coder_timeout,
        )
    finally:
        containers.stop_container(name)

    if not turn.succeeded:
        notes.append(
            f"Copilot fix turn failed (exit {turn.exit_code}); comments left "
            "unanswered — respond manually"
        )
        post_pr_comment(
            wt,
            pr_number,
            "story-develop attempted an automated response to Copilot's "
            f"review but the coder turn failed.\n\n{AUTOMATED_MARKER}",
        )
        return DeliveryOutcome(
            pr_url=pr_url,
            pr_number=pr_number,
            copilot_requested=True,
            copilot_reviewed=True,
            comments_count=len(comments),
            notes=tuple(notes),
        )

    # per-finding coder responses (fixed/disputed + public one-liner)
    responses: dict[str, Any] = {}
    coder_path = config.handoff_dir / coder_handoff
    try:
        coder_parsed = handoff.parse_review_handoff(
            coder_path.read_text(encoding="utf-8")
        )
        responses = {f.finding_id: f for f in coder_parsed.findings}
    except Exception:  # tolerant: replies degrade gracefully
        notes.append("coder handoff unreadable; replies use generic text")

    new_sha = git.commit_all(
        wt, f"story-develop copilot round: {title}", exclude=[".handoff"]
    )
    fix_committed = new_sha is not None

    # regression gate on the fix commit; RED => do NOT push the fix
    fix_pushed = False
    gate_verdict: str | None = None
    if fix_committed:
        gate_cmd = _resolve_gate_command(config, wt)
        gate = (
            _run_gate(config, wt, new_sha, fix_round, gate_cmd)
            if gate_cmd is not None
            else None
        )
        gate_verdict = gate.verdict if gate else None
        if gate is None or gate.passed:
            push_branch(wt, result.branch)
            fix_pushed = True
        else:
            notes.append(
                "Copilot fix NOT pushed: test gate "
                f"{gate.verdict} on the fix commit (kept locally in the worktree)"
            )
            post_pr_comment(
                wt,
                pr_number,
                "story-develop prepared a fix for Copilot's comments but the "
                f"regression test gate came back {gate.verdict}, so it was NOT "
                f"pushed. The candidate fix is in the run worktree.\n\n"
                f"{AUTOMATED_MARKER}",
            )

    # per-thread replies
    replies = 0
    for fid, comment in id_to_comment.items():
        f = responses.get(fid)
        disputed = f is not None and f.status == "disputed"
        coder_response = f.coder_response if f is not None else ""
        held_back = (
            gate_verdict
            if (not disputed and fix_committed and not fix_pushed)
            else None
        )
        body_text = reply_body(
            fixed=not disputed and fix_pushed,
            sha=new_sha if fix_pushed else None,
            coder_response=coder_response,
            held_back_verdict=held_back,
        )
        if post_thread_reply(wt, repo, pr_number, comment.comment_id, body_text):
            replies += 1

    return DeliveryOutcome(
        pr_url=pr_url,
        pr_number=pr_number,
        copilot_requested=True,
        copilot_reviewed=True,
        comments_count=len(comments),
        fix_committed=fix_committed,
        fix_pushed=fix_pushed,
        fix_gate_verdict=gate_verdict,
        replies_posted=replies,
        notes=tuple(notes),
    )
