"""PR delivery (T9, PRD decision #9; slimmed by S2 slice D).

After the panel approves, the trusted HOST-side plugin process (never an
agent container — agents have no push credentials) pushes the branch and opens
a PR via ``gh``. **Delivery ends when the PR is open** (plus best-effort
notify / review-request calls): the inline Copilot wait-and-fix round that
used to run here was retired by S2 slice D (gate 15690a0e — its shared
timeout starved the comment wait, and it saw only reviews loom itself
requested). Post-delivery review handling is the github-watcher's
external-review ingestion + ``converge --from-github`` remediation; the
optional per-project / per-task `develop_copilot_review` dial fires one
FIRE-AND-FORGET review request at PR open.

Layered like :mod:`containers` / :mod:`test_gate`: pure builders up top,
thin ``gh`` / ``git`` wrappers at the bottom (monkeypatched in tests).
"""

from __future__ import annotations

import logging
import subprocess
from dataclasses import dataclass, field
from pathlib import Path

from lithos_loom.github_client import GitHubError, parse_github_ref
from lithos_loom.github_models import (
    AUTOMATED_REPLY_MARKER,
    FIXED_REPLY_PREFIX,
)

from . import run_outcome
from .github_access import github_call, repo_name_with_owner

logger = logging.getLogger(__name__)

# Copilot's reviewer slug for the requested_reviewers POST (the display name
# "Copilot" silently no-ops — learned the hard way on this repo). Used only by
# the fire-and-forget `develop_copilot_review` hatch (gate 15690a0e decision):
# the inline wait-and-fix round is retired (S2 slice D) — the external-review
# sweep ingests whatever review lands, and `converge --from-github` remediates.
COPILOT_REVIEWER = "copilot-pull-request-reviewer[bot]"
# Alias of the shared vocabulary (github_models is the single source; the
# sweep and the converge external-findings fetch read the same constants).
AUTOMATED_MARKER = AUTOMATED_REPLY_MARKER


@dataclass(frozen=True)
class DeliveryOutcome:
    """What the delivery phase did (for the summary + Lithos posting).

    Slim since S2 slice D retired the inline Copilot round: delivery ends when
    the PR is open (plus best-effort notify / review-request calls). Review
    remediation happens post-delivery — the github-watcher ingests external
    reviews and dispatches ``converge --from-github``.
    """

    pr_url: str
    pr_number: int
    pushed: bool = True
    copilot_requested: bool = False
    """The `develop_copilot_review` hatch fired its one-shot request (no wait —
    the review, if any, arrives later and is ingested by the sweep)."""
    notes: tuple[str, ...] = field(default=())


# --- pure builders ------------------------------------------------------------


def parse_issue_ref(github_issue_url: str) -> tuple[str, int] | None:
    """``https://github.com/o/r/issues/42`` -> ``("o/r", 42)``; None if not.

    Thin adapter over :func:`~lithos_loom.github_client.parse_github_ref`,
    filtered to issue (not PR) refs.
    """
    ref = parse_github_ref(github_issue_url)
    if ref is None or ref.kind != "issue":
        return None
    return ref.repo, ref.number


def closes_line(github_issue_url: str | None, pr_repo: str) -> str:
    """The ``Closes …`` line linking the PR to its source issue, or ``""``.

    Same-repo issues use the short ``#N`` form; cross-repo issues need the
    full ``owner/repo#N`` form for GitHub's closing keywords to bind.
    """
    if not github_issue_url:
        return ""
    ref = parse_issue_ref(github_issue_url)
    if ref is None:
        return ""
    repo, number = ref
    if repo.lower() == pr_repo.lower():
        return f"Closes #{number}"
    return f"Closes {repo}#{number}"


def build_pr_body(
    *,
    description: str,
    acceptance_criteria: str | None,
    reviews_summary: str,
    rounds: int,
    gate_verdict: str | None,
    cost_usd: float,
    task_id: str | None,
    issue_closes: str = "",
) -> str:
    """The generated PR body: provenance + verdicts, not the whole log."""
    parts = ["## What", "", description.strip(), ""]
    if issue_closes:
        parts += [issue_closes, ""]
    if acceptance_criteria:
        parts += ["## Acceptance criteria", "", acceptance_criteria.strip(), ""]
    parts += [
        "## Review",
        "",
        f"- verdicts: {reviews_summary}",
        f"- rounds: {rounds}",
    ]
    if gate_verdict:
        parts.append(f"- test gate: {gate_verdict}")
    parts.append(f"- agent cost: ${cost_usd:.2f}")
    if task_id:
        parts.append(f"- Lithos task: `{task_id}`")
    parts += [
        "",
        "Per-round commits are intentional (the dialogue history); "
        "squash-merge keeps main clean.",
        "",
        "🤖 Generated by lithos-loom story-develop",
    ]
    return "\n".join(parts)


def reply_body(
    *,
    fixed: bool,
    sha: str | None,
    coder_response: str,
    held_back_verdict: str | None = None,
) -> str:
    """The per-thread reply: fix reference, held-back notice, or pushback.

    *held_back_verdict* covers the committed-but-not-pushed case (RED
    regression gate): the code DID change, so "Not changed" would be
    misleading — say what happened instead.
    """
    response = coder_response.strip() or "(no further detail given)"
    if held_back_verdict is not None:
        head = (
            f"A fix was prepared but NOT pushed — the regression test gate "
            f"came back {held_back_verdict} on the fix commit (see the PR "
            f"comment). Intended change: {response}"
        )
    elif fixed and sha:
        head = f"{FIXED_REPLY_PREFIX}{sha[:10]} — {response}"
    elif fixed:
        head = f"Addressed — {response}"
    else:
        head = f"Not changed — {response}"
    return f"{head}\n\n{AUTOMATED_MARKER}"


# --- thin gh / git wrappers (monkeypatched in tests) ---------------------------


def _run(
    args: list[str], *, cwd: Path, timeout: int = 120
) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        args, cwd=cwd, capture_output=True, text=True, timeout=timeout
    )


def push_branch(wt: Path, branch: str) -> None:
    """Host-side push of the worktree branch to origin. Raises on failure."""
    proc = _run(["git", "push", "-u", "origin", branch], cwd=wt, timeout=300)
    if proc.returncode != 0:
        raise RuntimeError(f"git push failed: {proc.stderr.strip()}")


class ForkPushUnsupported(RuntimeError):
    """The PR's head ref is not on ``origin`` (a fork PR), so converge cannot push
    to it under origin credentials (v1). The operator converges + fixes locally
    with ``--no-push``, or re-runs against a same-repo PR."""


class MergeRaceDetected(RuntimeError):
    """The PR head ref advanced on the remote since converge resolved it, so a push
    would not be a fast-forward. Converge stops rather than ``--force`` (which
    would clobber the concurrent commit); the operator re-runs to pick up the
    new tip."""


def push_to_pr_ref(
    wt: Path,
    local_branch: str,
    remote_ref: str,
    *,
    expected_remote_sha: str,
) -> str:
    """Push the reviewed worktree ``HEAD`` onto the PR's head ref *remote_ref*.

    Converge commits onto a fresh local branch at the PR head, so ``HEAD`` is a
    strict superset of *expected_remote_sha*. The invariant is stronger than
    "never do a non-fast-forward": push **only if the PR head is still exactly**
    *expected_remote_sha*, and push **exactly the reviewed HEAD**. Every guard
    operates on the SAME resolved ``HEAD`` sha so the checked and pushed objects
    can never disagree:

    * *local_branch* is required to resolve to ``HEAD`` — the caller names the
      branch it believes it is delivering, and we refuse if that is not the
      reviewed/gated commit (else a non-descendant *local_branch* could force the
      PR branch backward even with a matching lease);
    * an **append-only ancestry check** — the reviewed ``HEAD`` must descend from
      *expected_remote_sha*, so the leased update can only *add* commits;
    * an **atomic lease** — ``--force-with-lease=refs/heads/<ref>:<expected_sha>``
      updates only if ``origin``'s ref is *currently* at *expected_remote_sha*, so
      a branch deleted / advanced / rewound between the pre-check and the push is
      **rejected** (→ :class:`MergeRaceDetected`) instead of being silently
      recreated or overwritten. Together a guarded fast-forward — never a blind
      ``--force`` / history rewrite.

    A fast ``ls-remote`` pre-check still classifies a fork (ref absent on
    ``origin`` → :class:`ForkPushUnsupported`) and an already-advanced head before
    spending on the push. The pre-check queries the same fully-qualified
    ``refs/heads/<remote_ref>`` the lease and push name, and matches the returned
    ref name exactly — ``ls-remote`` patterns tail-match, so a bare branch name
    would also match an unrelated ``a/<remote_ref>``. Returns the exact ``HEAD``
    sha pushed; raises
    :class:`RuntimeError` on a caller/contract error or any other (auth / hook /
    network) push failure.
    """
    # The lease, the push, and the preflight must all name the SAME exact ref.
    # ls-remote treats its argument as a tail *pattern* — `feature` also matches
    # refs/heads/a/feature (which sorts first) — so query the fully-qualified ref
    # and key the lookup on the exact ref name, never on line order.
    dst = f"refs/heads/{remote_ref}"
    ls = _run(["git", "ls-remote", "--heads", "origin", dst], cwd=wt, timeout=120)
    if ls.returncode != 0:
        raise RuntimeError(f"git ls-remote origin {dst} failed: {ls.stderr.strip()}")
    remote_sha = ""
    for line in ls.stdout.splitlines():
        parts = line.split()
        if len(parts) == 2 and parts[1] == dst:
            remote_sha = parts[0]
            break
    if not remote_sha:
        raise ForkPushUnsupported(
            f"PR head ref {remote_ref!r} is not on origin (fork PR?); "
            "cannot push under origin credentials"
        )
    if remote_sha != expected_remote_sha:
        raise MergeRaceDetected(
            f"PR head ref {remote_ref!r} advanced remotely "
            f"({remote_sha[:10]} != expected {expected_remote_sha[:10]}); "
            "re-run converge"
        )
    # Resolve the ONE exact object we push — the reviewed + gated worktree HEAD —
    # and enforce every guard on THAT sha, so the ancestry check and the push can
    # never disagree about which commit lands on the PR branch.
    head = _run(["git", "rev-parse", "HEAD"], cwd=wt, timeout=120)
    if head.returncode != 0:
        raise RuntimeError(f"git rev-parse HEAD failed: {head.stderr.strip()}")
    head_sha = head.stdout.strip()

    # Contract: the caller's named branch must BE the reviewed HEAD. Otherwise we
    # would push a different object than the one reviewed/gated — and a
    # non-descendant local_branch could force the PR branch backward even though
    # the lease matches and HEAD descends from expected. Refuse rather than push
    # the wrong commit.
    lb = _run(["git", "rev-parse", "--verify", local_branch], cwd=wt, timeout=120)
    if lb.returncode != 0:
        raise RuntimeError(f"git rev-parse {local_branch} failed: {lb.stderr.strip()}")
    if lb.stdout.strip() != head_sha:
        raise RuntimeError(
            f"local branch {local_branch!r} ({lb.stdout.strip()[:10]}) is not the "
            f"reviewed HEAD ({head_sha[:10]}); refusing to push a different commit"
        )

    # Append-only guard on the EXACT object being pushed: the reviewed HEAD must
    # descend from the expected head, so the leased update can only fast-forward
    # (never rewind the contributor's history). In normal converge use this always
    # holds (the worktree was cut AT expected_remote_sha).
    anc = _run(
        ["git", "merge-base", "--is-ancestor", expected_remote_sha, head_sha],
        cwd=wt,
        timeout=120,
    )
    # --is-ancestor exits 1 for "not an ancestor" and 128 for a fatal error (bad
    # object, repo corruption) — only rc 1 is the race; "re-run converge" would
    # be misleading guidance for a broken repo.
    if anc.returncode == 1:
        raise MergeRaceDetected(
            f"reviewed HEAD {head_sha[:10]} does not descend from the expected "
            f"head {expected_remote_sha[:10]} (it changed under converge); "
            "re-run converge"
        )
    if anc.returncode != 0:
        raise RuntimeError(
            f"git merge-base --is-ancestor failed (rc {anc.returncode}): "
            f"{anc.stderr.strip()}"
        )
    # Atomic compare-and-swap: the lease pins origin's ref to expected_remote_sha,
    # closing the ls-remote→push TOCTOU window; we push the exact reviewed sha to
    # the fully-qualified branch ref. A deleted / advanced / rewound ref is
    # rejected ("stale info") rather than silently recreated or overwritten.
    proc = _run(
        [
            "git",
            "push",
            f"--force-with-lease={dst}:{expected_remote_sha}",
            "origin",
            f"{head_sha}:{dst}",
        ],
        cwd=wt,
        timeout=300,
    )
    if proc.returncode != 0:
        # A lease failure ("stale info") or a non-fast-forward / fetch-first
        # rejection is a race (the remote changed) → merge_race. A hook /
        # branch-protection / permission rejection also says "rejected" but
        # re-running converge won't help — those (and auth / network) stay a
        # generic RuntimeError.
        stderr = proc.stderr.strip()
        low = stderr.lower()
        if "stale info" in low or "fast-forward" in low or "fetch first" in low:
            raise MergeRaceDetected(
                f"push to {remote_ref!r} rejected — the head changed remotely "
                f"(expected {expected_remote_sha[:10]}); re-run converge: {stderr}"
            )
        raise RuntimeError(f"git push to {remote_ref} failed: {stderr}")
    return head_sha  # the exact sha pushed (== the reviewed HEAD)


def create_pr(wt: Path, *, branch: str, base: str, title: str, body: str) -> str:
    """Open the PR; returns its URL. Raises on failure."""
    proc = _run(
        [
            "gh",
            "pr",
            "create",
            "--head",
            branch,
            "--base",
            base,
            "--title",
            title,
            "--body",
            body,
        ],
        cwd=wt,
        timeout=300,
    )
    if proc.returncode != 0:
        raise RuntimeError(f"gh pr create failed: {proc.stderr.strip()}")
    url = proc.stdout.strip().splitlines()[-1].strip()
    if not url.startswith("http"):
        raise RuntimeError(f"gh pr create returned no URL: {proc.stdout!r}")
    return url


def pr_number_from_url(url: str) -> int:
    """Extract the PR number from a canonical GitHub PR URL; raise if it can't.

    Thin adapter over :func:`~lithos_loom.github_client.parse_github_ref`; the
    hard failure (vs. ``None``) is deliberate — delivery has a real PR URL here.
    """
    ref = parse_github_ref(url)
    if ref is None or ref.kind != "pull":
        raise RuntimeError(f"cannot parse PR number from {url!r}")
    return ref.number


def request_copilot(repo: str, pr_number: int) -> bool:
    """Request the Copilot reviewer; False (logged) on failure — non-fatal."""
    try:
        github_call(lambda c: c.request_reviewers(repo, pr_number, [COPILOT_REVIEWER]))
    except GitHubError as exc:
        logger.warning(
            "story-develop: requesting Copilot on %s#%d failed: %s",
            repo,
            pr_number,
            exc,
        )
        return False
    return True


def request_operator_review(repo: str, pr_number: int, login: str) -> str:
    """Request *login* as a reviewer on the PR; assign them if they authored it.

    Best-effort and non-fatal (mirrors :func:`request_copilot`): never raises,
    logs on failure. GitHub forbids requesting review from the PR *author* (HTTP
    422) — the common case when loom runs under the operator's own ``gh`` auth —
    so on that error we fall back to *assigning* the PR to them, which is allowed
    for self and still fires a native GitHub notification.

    Returns ``"review_requested"``, ``"assigned"``, or ``"failed"``.
    """
    try:
        github_call(lambda c: c.request_reviewers(repo, pr_number, [login]))
        return "review_requested"
    except GitHubError as exc:
        # Only the specific self-author 422 ("Review cannot be requested from
        # pull request author") falls back to assigning. Every other failure —
        # a bad login, a non-collaborator, repo policy, or any other 422 — is a
        # real failure the operator should see, NOT silently downgraded to an
        # assignee.
        if "pull request author" not in str(exc):
            logger.warning(
                "story-develop: requesting review from %s on %s#%d failed: %s",
                login,
                repo,
                pr_number,
                exc,
            )
            return "failed"

    try:
        github_call(lambda c: c.add_assignees(repo, pr_number, [login]))
        return "assigned"
    except GitHubError as exc:
        logger.warning(
            "story-develop: assigning %s to %s#%d failed: %s",
            login,
            repo,
            pr_number,
            exc,
        )
        return "failed"


def post_thread_reply(repo: str, pr_number: int, comment_id: int, body: str) -> bool:
    try:
        github_call(
            lambda c: c.create_review_comment_reply(repo, pr_number, comment_id, body)
        )
    except GitHubError as exc:
        logger.warning(
            "story-develop: reply to comment %d failed: %s",
            comment_id,
            exc,
        )
        return False
    return True


def post_pr_comment(repo: str, pr_number: int, body: str) -> bool:
    try:
        github_call(lambda c: c.create_issue_comment(repo, pr_number, body))
    except GitHubError as exc:
        logger.warning("story-develop: PR comment failed: %s", exc)
        return False
    return True


# --- orchestration --------------------------------------------------------------

# Overhead beyond the bounded agent phases — the worktree pushes (push_branch
# runs twice, start + fix, each with a 300s timeout) plus the gh API calls (PR
# open, reviewer/Copilot requests, per-comment replies — _run's 120s timeout
# each). A crashed delivery only takes longer to declare dead if this is too
# large, whereas too small re-opens the false-timeout; so it is deliberately
# generous (a healthy run is never timed out).
_DELIVERY_OVERHEAD_SECONDS = 1800


def delivery_budget_seconds(config) -> int:
    """Upper bound on the wall-clock :func:`deliver` can legitimately spend (#189).

    `develop attach` records a delivery deadline from this (via
    :func:`run_outcome.record_delivery_deadline` — the develop-run marker contract
    lives in :mod:`run_outcome`) so it can bound a *crashed* delivery without ever
    timing out a *healthy* slow one. Since S2 slice D retired the inline Copilot
    round, delivery has **no agent phase**: it is the branch pushes, the PR open,
    and the best-effort notify / review-request gh calls — all covered by the flat
    overhead margin. **Keep in sync with deliver() if a phase is added.**

    That attach's no-deadline fallback (``run_outcome.DELIVERY_FALLBACK_SECONDS``)
    stays above this budget — so it can't false-fire on a healthy default-config
    run — is enforced by the executed invariant
    ``test_delivery_fallback_exceeds_the_full_default_delivery_budget``, not prose.
    """
    del config  # the remaining bound is config-independent; kept for the seam
    return _DELIVERY_OVERHEAD_SECONDS


def deliver_guarded(
    config,
    result,
    *,
    open_pr: bool,
    copilot_review: bool,
    github_issue_url: str | None,
    task_id: str | None,
) -> tuple[DeliveryOutcome | None, str | None]:
    """Guarded PR delivery for an approved run — shared daemon/standalone seam.

    The single develop→deliver seam both ``__main__`` entry points call, so the
    #189 / #194 delivery contract is enforced identically on both surfaces instead
    of living in two hand-kept copies (the asymmetry ARCH-1.S3 fixes: standalone
    used to complete the task + exit 0 on a failed delivery). Returns
    ``(delivery, error)``:

    - ``(None, None)`` — nothing to deliver (``open_pr`` off, or the run wasn't
      approved). The caller renders "skipped" / nothing.
    - ``(DeliveryOutcome, None)`` — delivered.
    - ``(None, reason)`` — ``deliver()`` raised before a PR opened (#194). An
      approved dialogue with no PR is NOT a clean success, so the reason is
      returned for the caller to map to a non-success (daemon: ``result.json``
      failed + ``EXIT_FAILED``; standalone: skip ``--complete-on-approval`` + exit
      non-zero). The failure is recorded in the run's private ``delivery.json``
      (:func:`run_outcome.record_delivery_failure`) so ``develop attach`` reports
      it terminally rather than waiting out the #189 deadline.

    Records the #189 delivery deadline before delivery starts, so attach can bound
    a crashed/orphaned delivery without timing out a healthy slow one. The marker
    writers live in :mod:`run_outcome` (ARCH-3.R2); this only calls them.
    """
    if not (open_pr and result.approved):
        return None, None
    run_outcome.record_delivery_deadline(
        config.run_dir,
        budget_seconds=delivery_budget_seconds(config),
    )
    try:
        delivery = deliver(
            config,
            result,
            copilot_review=copilot_review,
            github_issue_url=github_issue_url,
            task_id=task_id,
        )
    except Exception as exc:  # delivery failure must not sink the run (#194)
        logger.exception("story-develop PR delivery failed")
        reason = str(exc)
        run_outcome.record_delivery_failure(config.run_dir, reason=reason)
        return None, reason
    return delivery, None


def deliver(
    config,
    result,
    *,
    copilot_review: bool = False,
    github_issue_url: str | None = None,
    task_id: str | None = None,
) -> DeliveryOutcome:
    """Push the approved branch and open the PR. Delivery ends there.

    Once :func:`create_pr` returns, the PR exists — so any later failure must NOT
    lose its url. The post-open work is delegated to :func:`_deliver_after_open`,
    and a raise there degrades to a delivered-with-notes outcome **carrying the
    url** (#192) rather than propagating — which would otherwise strand the
    operator with an approved run and no PR in the `attach` summary.
    """
    wt: Path = result.worktree
    notes: list[str] = []

    push_branch(wt, result.branch)
    repo = repo_name_with_owner(wt)
    title = config.description.strip().splitlines()[0][:90]
    body = build_pr_body(
        description=config.description,
        acceptance_criteria=config.acceptance_criteria,
        reviews_summary=" ".join(f"[{r.reviewer}]={r.status}" for r in result.reviews),
        rounds=result.rounds,
        gate_verdict=result.test_gate.verdict if result.test_gate else None,
        cost_usd=result.total_cost_usd,
        task_id=task_id,
        issue_closes=closes_line(github_issue_url, repo),
    )
    pr_url = create_pr(
        wt, branch=result.branch, base=config.base_branch, title=title, body=body
    )
    pr_number = pr_number_from_url(pr_url)
    logger.info("story-develop %s: opened PR %s", config.run_id, pr_url)

    try:
        return _deliver_after_open(
            config,
            result,
            wt=wt,
            repo=repo,
            title=title,
            pr_url=pr_url,
            pr_number=pr_number,
            notes=notes,
            copilot_review=copilot_review,
        )
    except Exception as exc:
        # The PR is already open; never strand its url on a later failure (#192).
        logger.warning(
            "story-develop %s: delivery did not finish after opening %s: %s",
            config.run_id,
            pr_url,
            exc,
        )
        return DeliveryOutcome(
            pr_url=pr_url,
            pr_number=pr_number,
            notes=(*notes, f"delivery did not finish after opening the PR: {exc}"),
        )


def _deliver_after_open(
    config,
    result,
    *,
    wt: Path,
    repo: str,
    title: str,
    pr_url: str,
    pr_number: int,
    notes: list[str],
    copilot_review: bool,
) -> DeliveryOutcome:
    """The post-PR-open delivery work: notify + the optional one-shot Copilot
    review request. Separated so :func:`deliver` can guarantee the PR url
    survives any failure here (#192).

    The inline wait-and-fix round that used to live here is retired (S2
    slice D; gate 15690a0e). ``copilot_review`` is the per-project / per-task
    `develop_copilot_review` dial resolved by the caller: when on, the request
    is FIRE-AND-FORGET — no wait, no fix turn — because the github-watcher's
    external-review ingestion picks up whatever review lands and
    ``converge --from-github`` remediates it under the S5b budget. Failure is
    logged, never fatal.
    """
    del wt, result, title  # retained in the seam for the #192 shape
    # #113: notify the operator their PR awaits review (native GitHub
    # notification). Best-effort; the note threads into every return below.
    if config.notify_github_login:
        notified = request_operator_review(repo, pr_number, config.notify_github_login)
        if notified == "review_requested":
            notes.append(f"requested review from @{config.notify_github_login}")
        elif notified == "assigned":
            notes.append(
                f"assigned PR to @{config.notify_github_login} "
                "(review can't be self-requested on your own PR)"
            )
        else:
            notes.append(f"could not notify @{config.notify_github_login} of the PR")

    if not copilot_review:
        return DeliveryOutcome(pr_url=pr_url, pr_number=pr_number, notes=tuple(notes))

    requested = request_copilot(repo, pr_number)
    if requested:
        notes.append("requested Copilot review (fire-and-forget; the sweep ingests it)")
    else:
        notes.append("Copilot review request failed; request manually if wanted")
    return DeliveryOutcome(
        pr_url=pr_url,
        pr_number=pr_number,
        copilot_requested=requested,
        notes=tuple(notes),
    )
